# Generated by Django 5.0.2 on 2024-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='desc',
            field=models.TextField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
