# Generated by Django 5.1.3 on 2024-12-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_estado_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='estado',
            name='modelo',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
