# Generated by Django 5.1.3 on 2024-12-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_estado_options_estado_modelo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('nombre', 'modelo')},
        ),
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='modelo',
            field=models.CharField(choices=[('proyecto', 'Proyecto'), ('documento', 'Documento'), ('actividad', 'Actividad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='estado',
            name='desc',
        ),
    ]
