# Generated by Django 5.1.3 on 2024-12-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
