# Generated by Django 5.1.3 on 2024-12-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0002_remove_empleado_fk_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fk_id_subarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarioApp.subarea'),
        ),
    ]
