# Generated by Django 5.1.3 on 2024-12-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_remove_actividad_nombre_alter_cliente_telefono'),
        ('usuarioApp', '0004_alter_empleado_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignar',
            old_name='fk_id_actividad',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='asignar',
            old_name='fk_rut_empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='empleado',
            old_name='fk_id_subarea',
            new_name='subarea',
        ),
        migrations.RenameField(
            model_name='subarea',
            old_name='fk_id_area',
            new_name='area',
        ),
        migrations.AlterUniqueTogether(
            name='asignar',
            unique_together={('empleado', 'actividad')},
        ),
    ]
