# Generated by Django 5.1.3 on 2024-12-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0005_rename_fk_id_actividad_asignar_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='subarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='usuarioApp.subarea'),
        ),
    ]
