# Generated by Django 5.1.3 on 2024-12-03 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Ingrese un RUT válido (formato: xxxxxxxx-x)', regex='^\\d{7,8}[-][0-9kK]$')])),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^(\\+?56)?(\\s?)(0?9)(\\s?)[9876543]\\d{7}$')])),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('link_drive', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('fk_id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='baseApp.estado')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
                ('fk_id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='baseApp.estado')),
                ('fk_id_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectoApp.documento')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('encargado_proyecto_pw', models.CharField(max_length=50)),
                ('encargado_proyecto_cl', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fk_id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='proyectoApp.cliente')),
                ('fk_id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='baseApp.estado')),
            ],
            options={
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='fk_id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectoApp.proyecto'),
        ),
    ]
