# Generated by Django 5.1.1 on 2024-11-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('fecha_creacion', models.DateField(auto_created=True)),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
