# Generated by Django 5.1.3 on 2024-12-12 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_estado_options_estado_color_estado_descripcion_and_more'),
        ('proyectoApp', '0001_initial'),
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre_actividad',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='encargado_proyecto_pw',
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarioApp.empleado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Actividad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='baseApp.estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Documento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='baseApp.estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarioApp.cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Proyecto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='baseApp.estado'),
        ),
        migrations.CreateModel(
            name='Asignar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='proyectoApp.actividad')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarioApp.empleado')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones',
                'unique_together': {('empleado', 'actividad')},
            },
        ),
    ]
