# Generated by Django 5.0.2 on 2024-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0002_alter_proyecto_fk_id_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fk_id_estado',
        ),
    ]
