# Generated by Django 5.1.3 on 2024-12-10 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0002_rename_fk_id_codigo_actividad_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido', regex='^(\\+?56)?(\\s?)(0?9)(\\s?)[98765432]\\d{7}$')]),
        ),
    ]
