# Generated by Django 5.1.3 on 2024-12-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0002_rename_nombre_proyecto_proyecto_nombre_and_more'),
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='usuarioApp.empleado'),
        ),
    ]
