# Generated by Django 5.1.3 on 2024-12-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_remove_actividad_nombre_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='revision',
        ),
    ]
