# Generated by Django 5.1.3 on 2024-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_actividad_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario del Encargado'),
        ),
    ]
