# Generated by Django 5.1.1 on 2024-11-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_modificacion',
            field=models.DateField(auto_created=True),
        ),
    ]
