# Generated by Django 5.1.3 on 2024-12-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_remove_documento_fk_id_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fk_id_estado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fk_id_estado',
        ),
    ]
