# Generated by Django 5.1.3 on 2024-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0004_alter_proyecto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
