# Generated by Django 5.1.3 on 2024-12-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_estado_options_estado_color_estado_descripcion_and_more'),
        ('proyectoApp', '0004_actividad_comentario'),
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectoApp.documento', verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='usuarioApp.empleado', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Actividad'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='baseApp.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
