# Generated by Django 5.1.3 on 2024-12-12 04:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_estado_options_estado_color_estado_descripcion_and_more'),
        ('proyectoApp', '0005_alter_actividad_comentario_and_more'),
        ('usuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Documento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='baseApp.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='link_drive',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Link Drive'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='proyectoApp.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarioApp.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='usuarioApp.empleado', verbose_name='Encargado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'modelo': 'Proyecto'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='baseApp.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
